### ISSUE TITLE
Is dotnet core based runtime , Beta or Production ready ?

### ISSUE THREAD

**Issue by paraspatidar** [apache/openwhisk-runtime-dotnet#13]
Hi ,
I last time explored this repository for openwhish with dotnet core in December 18 when it was just evolved.

However , on IBM function i dont see dotnet core as supported runtime and also at https://openwhisk.apache.org/documentation.html  in supported programming language section it is not updated.
Thus wanted to know if it is production ready or beat ready for production yet ?

**Comment by mrutkows** [comment]
@paraspatidar Thanks for letting us know that our website docs. are not keeping current with the latest runtimes that have been released by the OpenWhisk project.  I will immediately create a PR that updates the docs to include dotnet and our other runtimes recently released. Please feel free to help us keep our website or documentation up-to-date with a pull request.

**Comment by mrutkows** [comment]
@paraspatidar In terms of downstream consumers of the Apache OpenWhisk open source such as IBM Cloud Functions supporting dotnet (or other runtime), these Serverless providers are free to choose which runtimes they wish to support (or even providing other runtimes not in the apache OW project or runtimes that extend the OW runtimes).

It would best to seek answers about specific runtime support considerations from the ICF product team directly.  I would suggest using the "contact" or live web chat options to pose your question.  I believe you can find these options here https://www.ibm.com/cloud/functions (without having an account) or here: https://cloud.ibm.com/unifiedsupport/supportcenter (if you have an account).   I know for a fact the support staff finds the appropriate product team to provide official answers.  

In any case, ICF does support "bring-your-own" runtimes (aka "black box") images of runtimes and this is always an option for any language runtime/library configuration you want to run to support your applications with its existing dependencies/environment.

**Comment by mrutkows** [comment]
@paraspatidar closing this issue as the website docs. will be updated using PR https://github.com/apache/incubator-openwhisk-website/pull/399 against the website repo.  As you can see they are now cross-referenced.

**Comment by paraspatidar** [comment]
@mrutkows Thanks for quick action.
The main thing which I am looking here is that we shall be planing to use it under out own Kubernetes cluster as a part of server less.
so far we have evaluated some other options like **Kubeless** & **Fission**  , in the similar way wanted to know if OW dotnetcore runtime implementation  is fully functional without any glitches to be used in production as server-less option ?
For example in terms of :
Auto healing , HPA , autoscale  up / down  ,  persistent storage  etc.
If you could help on the same?

**Comment by rabbah** [comment]
@paraspatidar openwhisk is designed differently from the projects you mention and the core serverless functions capabilies are not part of any language runtime for a function which must only implement a narrow interface for life cycle management of a single function as described here https://github.com/apache/incubator-openwhisk/blob/master/docs/actions-new.md if you're interested in the details.

The openwhisk control and dataplane itself handles auto-scaling function containers up/down etc. That's covered by this repo https://github.com/apache/incubator-openwhisk.

OpenWhisk has been in production/GA at IBM for several years, and offered as a service by Adobe I/O Runtime, and there are other installations on prem as well from large organizations. 

If you find a specific issue with the dotnet runtime, please let us know here. If you have general questions about openwhisk, please use the Apache dev list or open an issue there https://github.com/apache/incubator-openwhisk/issues.
