### ISSUE TITLE
"Cannot invoke an uninitialized action." error occurs intermittently

### ISSUE THREAD

**Issue by sechunOH** [apache/openwhisk-runtime-dotnet#28]
Thanks for adding dotnet runtime to openwhisk.

I created action with sample code but sometimes errors occur when stress tests.
I debuged with console log and I found that "/run" was called before run(Run class) object is returned.

I fixed(moved) some codes and tested. Then no error occurred any more.
https://github.com/sechunOH/openwhisk-runtime-dotnet/pull/1

But I am not a dotnet programmer, so I'm not sure if the codes I fixed fits the dotnet grammar.

Is it okay if I make a pull request? can someone review it?

**Comment by style95** [comment]
@sechunOH Thank you for the contribution.
I believe @shawnallen85 can review it.
Please open a pr :)

**Comment by shawnallen85** [comment]
@sechunOH Can you provide the stress test you had performed and I can review the code and duplicate the issue and validate the resolution? Thanks!!

**Comment by sechunOH** [comment]
@shawnallen85 
I found history and the error occurred not only on stress test.
I created cron trigger(using alarm package) consisting of two or more same actions with option "*/1 * * * *"
Then I was waiting a few hours or a day until "running result: not ok" appears. (in invoker log)

```
< Action info >

Action is a dotnet sample action.

action download: https://github.com/sechunOH/sample-actions/blob/master/helloDotNet.zip
main: Apache.OpenWhisk.Example.Dotnet::Apache.OpenWhisk.Example.Dotnet.Hello::Main


< Test environment spec >

4core 4G mem VM 2EA : 2-controller deployed per vm
4core 4G mem VM 3EA : 1-invoker deployed per vm

Controller heap : 2G
Invoker heap : 2G, user-memory : 2048

no prewarmed container provided for dotnet action
```

First, if you duplicate this issue, I will open a pr.
if you need more informations, please reply. thanks!

**Comment by shawnallen85** [comment]
Alrighty -- I finally got to reviewing this. The only change I believe that needs to happen is in Startup.cs for both 2.2 and 3.0.

We need to check if run is null before returning the ok.
~ line 43
                    if (httpContext.Request.Path.Equals(initPath))
                    {
                        run = await init.HandleRequest(httpContext);
                        if(run != null)
                            await httpContext.Response.WriteResponse(200, "OK");
                        return;
                    }

**Comment by sechunOH** [comment]
@shawnallen85 
Ok. I added that codes and opened a pr. (https://github.com/apache/openwhisk-runtime-dotnet/pull/29)
could you please review it?
