### ISSUE TITLE
Add example using asynchronous returns

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk-runtime-dotnet#46]
Currently I don't think there is a way to return a Future from the .NET action, making it less convenient to write asynchronous functions.

**Comment by shawnallen85** [comment]
We support async/await methods in the .NET runtime.

https://docs.microsoft.com/en-us/dotnet/csharp/async

The [testEchoNoWrite](https://github.com/apache/openwhisk-runtime-dotnet/blob/66449cb972a547825b8ca40c4159bf933097edd6/tests/src/test/scala/actionContainers/DotNet3_1ActionContainerTests_2_2.scala#L54) test (in all runtimes) should be calling this [method](https://github.com/apache/openwhisk-runtime-dotnet/blob/66449cb972a547825b8ca40c4159bf933097edd6/tests/dotnetshared/Echo.cs#L31), which is asynchronous.

**Comment by rabbah** [comment]
Thanks! Indeed this is what I was looking for. We should add this to the docs. The particular use case I ran into was related to making an http request. Retitling.

**Comment by shawnallen85** [comment]
This'll be resolved here: https://github.com/apache/openwhisk-runtime-dotnet/pull/50
