### ISSUE TITLE
Question: how to log to activations using dotnet and openwhisk?

### ISSUE THREAD

**Issue by paul42** [apache/openwhisk-runtime-dotnet#59]
Hey All, love openwhisk so far, I've got it running on a small 2-node vm cluster, using the helm chart, doing the examples in dotnet and having a good time so far, but noticing that I'm not getting any logs when I try `wsk activation logs -l` or on any of my invokes - I'm trying to do the 'conductor' docs right now so I don't know if that would affect it, but when I try a `Console.Writeline()` or `Console.Out.Writeline()` I don't see anything in the logs - is there a correct way to write logs out?

Thanks,
Paul

**Comment by rabbah** [comment]
Hmm that's the way to logs from the function. Cross linking https://github.com/apache/openwhisk/issues/5168.

**Comment by paul42** [comment]
solved in other issue - used docker runtime with config file that uses json-file and very basic openebs persistence
