### ISSUE TITLE
kind 'dotnet:2.1' not in Set

### ISSUE THREAD

**Issue by shall3790** [apache/openwhisk-runtime-dotnet#6]
Hello,

I'm running the tutorial off your README and seeing the following error:

wsk action create helloDotNet helloDotNet.zip --main Apache.OpenWhisk.Example.Dotnet::Apache.OpenWhisk.Example.Dotnet.Hello::Main --kind dotnet:2.2
error: Unable to create action 'helloDotNet': The request content was malformed:
kind 'dotnet:2.2' not in Set(php:7.1, nodejs:8, swift:3, nodejs, blackbox, java, sequence, nodejs:6, python:3, python, python:2, swift, swift:3.1.1) (code 224)
Run 'wsk --help' for usage.

I've installed openwhisk on a local openshift cluster with no errors:
oc process -f https://git.io/vpnUR | oc create -f -

Any ideas? Thanks.

**Comment by dgrove-oss** [comment]
I'd guess that the openshift deployment runtime.json doesn't include dotnet as a runtime kind.  You need to add a stanza like the one at https://github.com/apache/incubator-openwhisk/blob/master/ansible/files/runtimes.json#L270 so that OpenWhisk will know what to do with a `dotnet` kind.

**Comment by shall3790** [comment]
Thank you!
