### ISSUE TITLE
Docker image for arm64

### ISSUE THREAD

**Issue by gleono** [apache/openwhisk-runtime-dotnet#87]
Hello! I stumbled upon this project and it really caught my curiosity. However, when I was trying to set it up on my machine (M1 Mac) I had to build a new docker image and found that it was broken.

I decided to investigate the issue a little bit more and ran the built image locally using the command `./gradlew distDocker` and I got the following error:
```
Failed to load /app/libhostpolicy.so, error: Error relocating /app/libhostpolicy.so: unsupported relocation type 7
An error occurred while loading required library libhostpolicy.so from [/app/]
```

Fixing this would make it easier to test changes to the runtime on a M1 mac.

I have a [branch](https://github.com/gleono/openwhisk-runtime-dotnet/tree/docker-aspnet-runtime) with a possible fix for this, but I don't have access to a x64 machine to test the image.

I tested the changes locally by running OpenWhisk as a standalone container on Docker and used `wsk` with the `--docker` argument and it seemed to work fine :)

I don't know how to run the rest of the tests with this setup. Is the recommendation to use Ansible for setting up local environment?

**Comment by style95** [comment]
I suppose if you open a PR with the branch, the CI tests would run on x86 machine.

**Comment by unfixa1** [comment]
libhostpolicy.so error: This error is usually caused by incompatible libraries or relocation types. You mentioned that there is already a possible fix. Consider submitting this fix as a Pull Request (PR) so that the CI tests will run on an x86 machine, which can verify that your changes are effective.
It is recommended to replace docker with a tool such as [servbay](www.servbay.com), which has fewer bugs than docker on mac

**Comment by gleono** [comment]
The image should be able to be built on arm64 and amd64 now. However, it looks like there is a bigger effort of modifying the gradle distDocker task to produce and push images for both platforms (See apache/openwhisk#5503).

**Comment by shawnallen85** [comment]
The latest completed PR should have this being built for both amd64 and arm64 architectures. @gleono Do you feel this issue can be resolved/closed?

**Comment by gleono** [comment]
I think so! I just tested on my machine and it works. I am excited for the next release that publishes both images. Thanks!
